spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${CONNECTION_STRING:jdbc:postgresql://localhost:5432/postgres}
    username: postgres
    password: 1324Qwex
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath*:database/initDB.sql
      data-locations: classpath*:database/populateDB.sql