insert into employees (first_name, last_name, department, salary) values ('Christin', 'Sodory', 'Marketing', 1178);
insert into employees (first_name, last_name, department, salary) values ('Alissa', 'Gaveltone', 'Business Development', 1413);
insert into employees (first_name, last_name, department, salary) values ('Mace', 'Balsdone', 'Services', 968);
insert into employees (first_name, last_name, department, salary) values ('Leontyne', 'Khomich', 'Accounting', 1926);
insert into employees (first_name, last_name, department, salary) values ('Linc', 'Dibbe', 'Product Management', 827);
insert into employees (first_name, last_name, department, salary) values ('Hamnet', 'Dabbs', 'Product Management', 853);
insert into employees (first_name, last_name, department, salary) values ('Royal', 'Ferencowicz', 'Human Resources', 1668);
insert into employees (first_name, last_name, department, salary) values ('Carolyn', 'Elger', 'Legal', 594);
insert into employees (first_name, last_name, department, salary) values ('Damita', 'Charlton', 'Sales', 1404);
insert into employees (first_name, last_name, department, salary) values ('Ambrosi', 'Potteridge', 'Services', 713);
insert into employees (first_name, last_name, department, salary) values ('Lauritz', 'Rhubottom', 'Research and Development', 1583);
insert into employees (first_name, last_name, department, salary) values ('Dill', 'Dysert', 'Services', 1499);
insert into employees (first_name, last_name, department, salary) values ('Elnora', 'O'' Donohoe', 'Human Resources', 630);
insert into employees (first_name, last_name, department, salary) values ('Valeria', 'Fuke', 'Business Development', 1197);
insert into employees (first_name, last_name, department, salary) values ('Lorilyn', 'MacKnight', 'Engineering', 953);
insert into employees (first_name, last_name, department, salary) values ('Stanislaw', 'Tretwell', 'Marketing', 1913);
insert into employees (first_name, last_name, department, salary) values ('Eugenius', 'Botcherby', 'Legal', 1656);
insert into employees (first_name, last_name, department, salary) values ('Philippa', 'Dunkerly', 'Accounting', 1266);
insert into employees (first_name, last_name, department, salary) values ('Hillary', 'Quantick', 'Services', 997);
insert into employees (first_name, last_name, department, salary) values ('Harli', 'Roggerone', 'Human Resources', 1708);
insert into employees (first_name, last_name, department, salary) values ('Candis', 'Bason', 'Training', 1500);
insert into employees (first_name, last_name, department, salary) values ('Blondell', 'Ebbetts', 'Accounting', 1915);
insert into employees (first_name, last_name, department, salary) values ('Abba', 'Yves', 'Research and Development', 741);
insert into employees (first_name, last_name, department, salary) values ('Tammara', 'Caherny', 'Sales', 1545);
insert into employees (first_name, last_name, department, salary) values ('Eryn', 'Waddington', 'Marketing', 1511);
insert into employees (first_name, last_name, department, salary) values ('Kynthia', 'Shadbolt', 'Engineering', 819);
insert into employees (first_name, last_name, department, salary) values ('Eden', 'Fawdry', 'Business Development', 937);
insert into employees (first_name, last_name, department, salary) values ('Roseanne', 'Catcherside', 'Accounting', 1766);
insert into employees (first_name, last_name, department, salary) values ('Meridel', 'Paddemore', 'Marketing', 1646);
insert into employees (first_name, last_name, department, salary) values ('Kelly', 'Christal', 'Product Management', 1890);
insert into employees (first_name, last_name, department, salary) values ('Mandie', 'Busek', 'Human Resources', 1484);
insert into employees (first_name, last_name, department, salary) values ('Vanda', 'Yanshinov', 'Support', 883);
insert into employees (first_name, last_name, department, salary) values ('Kellia', 'Philipard', 'Services', 658);
insert into employees (first_name, last_name, department, salary) values ('Eugen', 'Drewes', 'Training', 1961);
insert into employees (first_name, last_name, department, salary) values ('Belva', 'Irving', 'Business Development', 1647);
insert into employees (first_name, last_name, department, salary) values ('Leese', 'Elsip', 'Research and Development', 1099);
insert into employees (first_name, last_name, department, salary) values ('Irvine', 'Castanie', 'Training', 1578);
insert into employees (first_name, last_name, department, salary) values ('Magnum', 'Lewknor', 'Research and Development', 1365);
insert into employees (first_name, last_name, department, salary) values ('Cynthy', 'Piper', 'Training', 1661);
insert into employees (first_name, last_name, department, salary) values ('Phaidra', 'Ditchfield', 'Sales', 1727);
insert into employees (first_name, last_name, department, salary) values ('Kayle', 'Prandin', 'Research and Development', 1865);
insert into employees (first_name, last_name, department, salary) values ('Crysta', 'Kellogg', 'Sales', 710);
insert into employees (first_name, last_name, department, salary) values ('Thedric', 'Forten', 'Marketing', 1335);
insert into employees (first_name, last_name, department, salary) values ('Dorella', 'Massy', 'Support', 1681);
insert into employees (first_name, last_name, department, salary) values ('Madlen', 'Arlott', 'Training', 1612);
insert into employees (first_name, last_name, department, salary) values ('Beilul', 'Callam', 'Training', 1159);
insert into employees (first_name, last_name, department, salary) values ('Rab', 'Pittle', 'Research and Development', 737);
insert into employees (first_name, last_name, department, salary) values ('Keane', 'Thunderman', 'Support', 989);
insert into employees (first_name, last_name, department, salary) values ('Kati', 'Cay', 'Research and Development', 1138);
insert into employees (first_name, last_name, department, salary) values ('Shem', 'Folkerd', 'Engineering', 827);
